name: conflux_codec
version: 0.0.1

dependencies:
  convert: ^2.1.1
  pointycastle: ^1.0.1
  typed_data: ^1.2.0
  sprintf: ^5.0.0
  ethereum_util:
    git:
      url: https://github.com/GreenAppers/ethereum_util

environment:
  sdk: ">=1.19.0 <3.0.0"