name: conflux_codec_demo
version: 0.0.1
publish_to: 'none'

dependencies:
  convert: ^3.0.0
  conflux_codec:
    path: ../
  ethereum_codec:
    git:
      url: https://github.com/nbltrust/dart-eth-transaction-codec.git
      ref: 2.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'
